CREATE TABLE STUDENT
(
SID INT,
NAME VARCHAR(20),
DOB VARCHAR(20),
PHYSICS INT,
CHEMISTRY INT,
MATHS INT
);


INSERT INTO STUDENT(SID,NAME,DOB,PHYSICS,CHEMISTRY,MATHS)
VALUES(01,'ALLEN','5-JULY-99',60,75,70),
(02,'WARD','15-JUNE-98',50,60,50),
(03,'MARTIN','03-JUNE-99',70,80,65),
(04,'SCOTT','15-APRIL-97',45,60,55),
(05,'KING','20-MARCH-99',55,50,75);

SELECT SID,NAME FROM STUDENT WHERE DOB =(SELECT MAX(DOB) FROM STUDENT);

SELECT * FROM STUDENT WHERE PHYSICS AND CHEMISTRY OR MATHS>40;

ALTER TABLE  STUDENT ADD COLUMN (AVERAGE INT DEFAULT(0), TOTAL INT DEFAULT(0));

SELECT NAME,MATHS FROM STUDENT WHERE MATHS=(SELECT MAX(MATHS) FROM STUDENT);

SELECT NAME,CHEMISTRY FROM STUDENT WHERE CHEMISTRY=(SELECT MIN(CHEMISTRY) FROM STUDENT);

UPDATE  STUDENT SET TOTAL= PHYSICS + CHEMISTRY + MATHS;

SELECT NAME,TOTAL FROM STUDENT ORDER BY TOTAL DESC;

UPDATE  STUDENT 
SET AVERAGE= (PHYSICS + CHEMISTRY + MATHS)/3;

ALTER TABLE STUDENT
RENAME COLUMN AVERAGE TO AVG_MARK;

SELECT AVG(TOTAL) as CLS_AVG FROM STUDENT;

SELECT NAME FROM STUDENT WHERE AVG_MARK>(SELECT AVG(TOTAL) FROM STUDENT);

SELECT COUNT(*) AS TOTAL FROM STUDENT WHERE AVG_MARK> (SELECT AVG(AVG_MARK) FROM STUDENT);